### ISSUE TITLE
虚拟机运行报错

### ISSUE THREAD

**Issue by RookieTerry** [piiperxyz/AniYa#1]
如图所示：
![Snipaste_2022-07-18_14-37-13](https://user-images.githubusercontent.com/77920425/179456622-ad54c005-0d43-4f1d-8869-3727a7cd85cf.png)

**Comment by piiperxyz** [comment]
你好，是直接运行的编译好的版本吗，能告知一下虚拟环境不，我测试的win10和win7都没问题

**Comment by RookieTerry** [comment]
是编译好的版本，虚拟机是win10企业版LTSC

**Comment by piiperxyz** [comment]
看报错信息是环境不支持OPENGL图形相关驱动，这个是fyne框架的问题，我这边无法解决，或者再调试下环境
