### ISSUE TITLE
stowaway这个怎么打包生成一个免杀exe呢

### ISSUE THREAD

**Issue by llx418** [piiperxyz/AniYa#10]

**Comment by piiperxyz** [comment]
正常go编译的少一些东西，导致无法使用donut，需要带上-buildmod=pie重新编译一个stowaway，然后用Aniya正常处理即可

**Comment by llx418** [comment]
试了下Mimikaze，但打包生成的result.exe不能输入输出

**Comment by piiperxyz** [comment]
我测试直接运行是没问题的，你的意思是后面带参数运行吗，那个可以考虑开发

**Comment by llx418** [comment]
windows go编译默认加上了-buildmod=pie，而且我把agent执行参数写死了再编译用Aniya处理也不行

**Comment by llx418** [comment]
我用的是32位stowaway

**Comment by piiperxyz** [comment]
如果你问题还没解决的话，可以发送邮件至0flyinbedxyz0@gmail.com深入沟通一下
