### ISSUE TITLE
编译后，打开中文乱码问题

### ISSUE THREAD

**Issue by qahehe** [piiperxyz/AniYa#14]
![image](https://github.com/piiperxyz/AniYa/assets/25258443/4353ba4d-b32a-4ab5-865c-bf54442df40b)
win10虚拟机，golang1.20.5编译完成打开后发现出现了编码问题

**Comment by flyinbedxyz** [comment]
大概率是fyne新版本的问题，可以试下用mod里的老版本

**Comment by qahehe** [comment]
![image](https://github.com/piiperxyz/AniYa/assets/25258443/1586a527-1de4-4fbd-a52b-35a447fb1a81)

go mod tidy后可以了，不乱码了
