### ISSUE TITLE
调用hide参数时闪退

### ISSUE THREAD

**Issue by imkitsch** [piiperxyz/AniYa#2]
隐藏窗口编译时闪退，但tmp文件夹存在，系统版本为win10

**Comment by piiperxyz** [comment]
BUG，马上发布一个修复的版本

**Comment by imkitsch** [comment]
其实可以取消windowsgui编译参数，使用github.com/lxn/win库来隐藏cmd窗体

**Comment by piiperxyz** [comment]
新版本发布了，可以再测试下，这个功能我一直不用。。。比较影响免杀效果，而且我记得命令行执行马子是没有黑框的，所以之前也没做测试
