### ISSUE TITLE
garble闪退问题

### ISSUE THREAD

**Issue by fgfxf** [piiperxyz/AniYa#9]
使用最新版，勾选garble功能后闪退。

另外经过测试，32位可以正常编译，建议楼主编译一份32位的上传到release

**Comment by piiperxyz** [comment]
garble需要安装，大家伙先把readme仔细看看。懂go语言的，自己调整go的编译参数编译32位，不懂go的我给你编译了32位的AniYa，生成木马的时候还是64位，所以感觉没必要，你是单独需要32位的AniYa还是32位的木马？

**Comment by NS-Sp4ce** [comment]
see #4

**Comment by fgfxf** [comment]
garble安装了啊，还是不行

**Comment by fgfxf** [comment]
可以了，thank u，我安装了garble，但是bin目录里没用，我从别处下载了一个garble.exe就好了

**Comment by a200934847** [comment]
> 可以了，thank u，我安装了garble，但是bin目录里没用，我从别处下载了一个garble.exe就好了

你联系方式多少大佬

**Comment by a200934847** [comment]
大佬我用这个免杀工具 生成卡窗口不动 是需要设置环境什么的吗

**Comment by fgfxf** [comment]
> 大佬我用这个免杀工具 生成卡窗口不动 是需要设置环境什么的吗

需要安装go语言环境，还要安装插件，go的bin目录里要有相关插件的exe文件，比如garble，安装了go的garble组件还不行，还有有win环境的exe文件。garble.exe百度就能搜到，然后我下载了一个放到了bin目录里。

**Comment by a200934847** [comment]
> > 大佬我用这个免杀工具 生成卡窗口不动 是需要设置环境什么的吗
> 
> 需要安装go语言环境，还要安装插件，go的bin目录里要有相关插件的exe文件，比如garble，安装了go的garble组件还不行，还有有win环境的exe文件。garble.exe百度就能搜到，然后我下载了一个放到了bin目录里。

我不会弄你能留个联系方式吗大佬 有偿 我弄一天了实在弄不好

**Comment by a200934847** [comment]
好吗 着急啊

**Comment by baooogang** [comment]
大佬，您好我是你的粉丝，我用aniya勾选garble生成会闪退，另生成EXE不上线，GO目录下面BIN文件夹只有两个应用，是不是哪里没弄对啊，我QQ575541107在线等，有偿。
